### ISSUE TITLE
Add Inventory Item(s)

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-mobile-signals-work-orders#27]
The goal here is for a Technician to be able to add an inventory item to a work order for the items they used to complete a job.

Start at [My Work Orders](https://atd.knack.com/test-data-tracker#my-work-orders3), go to the details of one (Ex: https://atd.knack.com/test-data-tracker#my-work-orders3/my-work-order-details2/5bb3b798b7748a2d06a4e87b/). Scroll down...

### Screenshot
<img width="735" alt="screen shot 2018-10-02 at 3 57 25 pm" src="https://user-images.githubusercontent.com/5697474/46376572-ef111d80-c65b-11e8-841f-22bb164bbb64.png">

**Comment by mateoclarke** [comment]
I'm blocked on this right now because the user I'm logged in with doesn't seem to have access to add inventory, even though they created this new Work Order.

Kind of related to issue #12. But maybe you could help me modify my user or let me know what I'm doing wrong so I can get a better screenshot of what this currently looks like. cc/ @dianamartin @johnclary

**Comment by johnclary** [comment]
You can edit your own account permissions in the builder. Find the Accounts object  at the bottom of the object listing. Then find your account record and add all the user roles.

On Oct 2, 2018, at 14:37, Mateo Clarke <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm blocked on this right now because the user I'm logged in with doesn't seem to have access to add inventory, even though they created this new Work Order.

Kind of related to issue #12<https://github.com/cityofaustin/react-knack/issues/12>. But maybe you could help me modify my user or let me know what I'm doing wrong so I can get a better screenshot of what this currently looks like. cc/ @dianamartin<https://github.com/dianamartin> @johnclary<https://github.com/johnclary>

**Comment by mateoclarke** [comment]
@johnclary Yup, I've tried modifying the account permissions for both `mateo.clarke@austintexas.gov` & `test-tech@austintexas.gov`. What am I doing wrong? 

![screen shot 2018-10-02 at 3 09 34 pm](https://user-images.githubusercontent.com/5697474/46374010-419b0b80-c655-11e8-8dcb-d9e3790b8731.png)

![screen shot 2018-10-02 at 3 09 43 pm](https://user-images.githubusercontent.com/5697474/46374011-419b0b80-c655-11e8-917c-0bf84389600b.png)

**Comment by mateoclarke** [comment]
@johnclary I think that link unblocks me. I was trying to get to a work order I was assigned to from the all work orders page: https://atd.knack.com/test-data-tracker#work-orders3/ so the Details Page it took me to from the table when I clicked on one of those items must be different from the view that includes the fields to Add Inventory Materials. Thanks!
